### ISSUE TITLE
Thanks for bringing this back to life

### ISSUE THREAD

**Issue by rmichela** [Justasic/Spigot-SSHD#3]
I saw your post on Reddit. It's great to see this old plugin revived. Great work!

**Comment by ZachyFoxx** [comment]
Thank you! We've worked hard on supporting modern versions of the game along with other APIs. Glad to see you're happy seeing it revived! :)

**Comment by Justasic** [comment]
I had been looking for a solution like this for a while and was so happy to find this! It needed a little work but I'm glad to bring it back to life and appreciate that you laid out most of the groundwork! If you ever want to work on it again I would be happy to let you tinker! 😁
